//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeHubApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeHubApp.AppResx", typeof(AppResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe: {0}  {1}.
        /// </summary>
        public static string AlarmContentKey {
            get {
                return ResourceManager.GetString("AlarmContentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellow will appear a list of detected alarms from recipe procedure.
        /// </summary>
        public static string AlarmDescriptText {
            get {
                return ResourceManager.GetString("AlarmDescriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alarms.
        /// </summary>
        public static string AlarmDetectedTitle {
            get {
                return ResourceManager.GetString("AlarmDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms Creations.
        /// </summary>
        public static string AlarmDetectHeaderKey {
            get {
                return ResourceManager.GetString("AlarmDetectHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm {0} | {1} minutes.
        /// </summary>
        public static string AlarmHeaderMessage {
            get {
                return ResourceManager.GetString("AlarmHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm was not configured to display information here.
        /// </summary>
        public static string AlarmNotConfKey {
            get {
                return ResourceManager.GetString("AlarmNotConfKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application could not find any alarm.
        /// </summary>
        public static string AlarmNotFoundKey {
            get {
                return ResourceManager.GetString("AlarmNotFoundKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Hub.
        /// </summary>
        public static string AppNameKey {
            get {
                return ResourceManager.GetString("AppNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Hub.
        /// </summary>
        public static string AppTitleKey {
            get {
                return ResourceManager.GetString("AppTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorKey {
            get {
                return ResourceManager.GetString("AuthorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryKey {
            get {
                return ResourceManager.GetString("CategoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ConfigKey {
            get {
                return ResourceManager.GetString("ConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete History.
        /// </summary>
        public static string DeleteHistoryKey {
            get {
                return ResourceManager.GetString("DeleteHistoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsKey {
            get {
                return ResourceManager.GetString("DetailsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string HistoryKey {
            get {
                return ResourceManager.GetString("HistoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingredients.
        /// </summary>
        public static string IngridentsKey {
            get {
                return ResourceManager.GetString("IngridentsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Ingredient.
        /// </summary>
        public static string MainIngredientKey {
            get {
                return ResourceManager.GetString("MainIngredientKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MoreKey {
            get {
                return ResourceManager.GetString("MoreKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forks.
        /// </summary>
        public static string PortionsKey {
            get {
                return ResourceManager.GetString("PortionsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procedure.
        /// </summary>
        public static string ProcedureKey {
            get {
                return ResourceManager.GetString("ProcedureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this App.
        /// </summary>
        public static string RateKey {
            get {
                return ResourceManager.GetString("RateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recents.
        /// </summary>
        public static string RecentsKey {
            get {
                return ResourceManager.GetString("RecentsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recipes.
        /// </summary>
        public static string RecipesKey {
            get {
                return ResourceManager.GetString("RecipesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchKey {
            get {
                return ResourceManager.GetString("SearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background.
        /// </summary>
        public static string SelectBackground {
            get {
                return ResourceManager.GetString("SelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsKey {
            get {
                return ResourceManager.GetString("SettingsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareKey {
            get {
                return ResourceManager.GetString("ShareKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Options.
        /// </summary>
        public static string ShareOptionsKey {
            get {
                return ResourceManager.GetString("ShareOptionsKey", resourceCulture);
            }
        }
    }
}
